name: pythia
channels:
- conda-forge
- nodefaults
dependencies:
- matplotlib
- myst-nb
- pandas
- pip
- pyyaml
- pre-commit
- python>=3.11,<3.12
- sphinx>=5.0,<6.0
- ablog
- pip:
  - sphinx-pythia-theme
