name: pythia
channels:
- conda-forge
- nodefaults
dependencies:
- matplotlib
- myst-nb
- pandas
- pip
- pyyaml
- pre-commit
- python>=3.9,<3.12
- sphinx-panels=0.6.0
- sphinx=4.5.0
- ablog
- pip:
  - sphinx-pythia-theme
