name: pythia
channels:
- conda-forge
- nodefaults
dependencies:
- ablog
- matplotlib
- myst-nb
- pandas
- pre-commit
- pyyaml
- pip
- pip:
  - git+https://github.com/ProjectPythia/sphinx-pythia-theme.git@theme-update
  - sphinx_design #will remove when changed above theme install to PyPI or conda
