name: pythia
channels:
- conda-forge
- nodefaults
dependencies:
- matplotlib
- myst-nb
- pandas
- pip
- pyyaml
- pre-commit
- sphinx-panels
- ablog
- sphinx-ext-jsonextract
- pip:
  - sphinx-pythia-theme
