name: pythia
channels:
- conda-forge
- nodefaults
dependencies:
- matplotlib
- myst-nb
- pandas
- pip
- pyyaml
- pre-commit
- sphinx-panels
- ablog
- pip:
  - git+https://github.com/ProjectPythia/sphinx-pythia-theme.git@theme-update
