name: Update User Metrics

on:
  schedule:
    # Weekly Every Monday at 1PM UTC
    - cron: '0 13 * * 1'

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Credentials
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.GOOGLE_ANALYTICS_API_CREDENTIALS }}
          filename: "credentials.json"
          is-executable: true
          working-directory: "."
      - run: export GOOGLE_APPLICATION_CREDENTIALS="credentials.json"

      - name: Set-Up Virtual Environment
        run: |
          python -m venv analytics-api
          source analytics-api/bin/activate
          pip install google-analytics-data

      - name: Get and Write Metrics to JSON
        # similarly, could save generated graphs to update more visually appealing metrics
        run: python get_metrics.py ${{ secrets.GA_PORTAL_ID }} ${{ secrets.GA_FOUNDATIONS_ID }} ${{ secrets.GA_COOKBOOKS_ID }}

      - name: Write Markdown File
        run: python write_metrics_md.py

      - name: Push Changes
        if: steps.Get-and-Write-Metrics.outputs == 1  # Conditional step execution
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add user_metrics.json
          git add ../portal/metrics.md
          git commit -m "Update user metrics"
          git push
