name: Update User Metrics

on:
  workflow_dispatch:

env:
  portal_id: ${{  secrets.GA4_PORTAL_ID }}
  foundations_id: ${{ secrets.GA4_FOUNDATIONS_ID }}
  cookbooks_id: ${{ secrets.GA4_COOKBOOKS_ID }}
  GOOGLE_ANALYTICS_CREDENTIALS: ${{ secrets.GOOGLE_ANALYTICS_CREDENTIALS }}

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set-Up Virtual Environment and Write Metris to JSON
        run: |
          python -m venv analytics-api
          source analytics-api/bin/activate
          pip install google-analytics-data

          curl -O https://raw.githubusercontent.com/jukent/projectpythia.github.io/main/.github/workflows/get-metrics.py
          python get-metrics.py
          ls

      - name: Write Markdown File
        run: |
          source analytics-api/bin/activate
          curl -O https://raw.githubusercontent.com/jukent/projectpythia.github.io/main/.github/workflows/write-metrics-md.py
          python write-metrics-md.py
