name: Update User Metrics

on:
  workflow_dispatch:

env:
  PORTAL_ID: ${{  secrets.PORTAL_ID }}
  FOUNDATIONS_ID: ${{ secrets.FOUNDATIONS_ID }}
  COOKBOOKS_ID: ${{ secrets.COOKBOOKS_ID }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
  ENCODED_CREDENTIALS: ${{ secrets.ENCODED_CREDENTIALS }}

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set-Up Virtual Environment
        run: |
          python -m venv analytics-api
          source analytics-api/bin/activate
          pip install google-analytics-data

      - name: Write Metrics to JSON
        run: |
          source analytics-api/bin/activate
          curl -O https://raw.githubusercontent.com/jukent/projectpythia.github.io/main/.github/workflows/get-metrics.py
          python get-metrics.py
          ls

      - name: Write Markdown File
        run: |
          source analytics-api/bin/activate
          curl -O https://raw.githubusercontent.com/jukent/projectpythia.github.io/main/.github/workflows/write-metrics-md.py
          python write-metrics-md.py
