name: deploy-site

# Only run this when the main branch changes
on:
  push:
  pull_request:
  workflow_dispatch:


# This job installs dependencies, build the site, and pushes it to `gh-pages`
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    if: github.repository == 'ProjectPythia/projectpythia.github.io'
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@master
        with:
          channels: conda-forge
          channel-priority: strict
          activate-environment: pythia
          auto-update-conda: false
          python-version: 3.8
          environment-file: ci/environment.yml
          mamba-version: '*'
          use-mamba: true

      - name: Build
        run: |
          conda env list
          cd portal
          make -j4 html
      - name: Zip the site
        run: |
          set -x
          set -e
          if [ -f site.zip ]; then
              rm -rf site.zip
          fi
          zip -r site.zip ./portal/_build/html
      - uses: actions/upload-artifact@v2
        with:
          name: site-zip
          path: ./site.zip

      - uses: actions/upload-artifact@v3
        with:
          name: site-zip
          path: ./site.zip
      # Push the site's HTML to github-pages
      - name: Deploy to GitHub pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          enable_jekyll: false
          cname: projectpythia.org
