name: nightly-build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”

jobs:
  automate-metrics:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Automate Metrics
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        run: |
          python -m venv analytics-api
          source analytics-api/bin/activate
          pip install google-analytics-data cartopy matplotlib

          python .github/workflows/get-metrics.py
          python .github/workflows/write-metrics-md.py
      - name: Upload zipped repo artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-w-metrics
          path: ./repo.zip

  build:
    needs: automate-metrics
    steps:
      upload-artifact:  # Assuming this is the step name on line 33 (adjust if different)
        uses: actions/upload-artifact@v4
        with:
          name: repo-w-metrics
          path: ./repo.zip
      build:
        if: ${{ github.repository_owner == 'ProjectPythia' }}
        uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
        with:
          environment_file: 'environment.yml'
          environment_name: pythia
          path_to_notebooks: 'portal'
          build_command: 'make -j4 html'

  link-check:
    if: ${{ github.repository_owner == 'ProjectPythia' }}
    uses: ./.github/workflows/sphinx-link-checker.yaml
    with:
      path_to_source: 'portal'

  deploy:
      needs: build
      uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
      with:
        cname: projectpythia.org
        publish_dir: 'portal/_build/html'
