name: nightly-build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”

jobs:
  build:
    if: ${{ github.repository_owner == 'ProjectPythia' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_file: 'ci/environment.yml'
      environment_name: pythia
      path_to_notebooks: 'portal'
      build_command: 'make -j4 html'
      use_cached_environment: 'false'
