name: publish-site

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@erogluorhan-patch-1
    with:
      environment_file: 'environment.yml'
      environment_name: pythia
      path_to_notebooks: 'portal'
      build_command: 'make -j4 html'

  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@erogluorhan-patch-1
    with:
      cname: projectpythia.org
      publish_dir: 'portal/_build/html'
