name: trigger-preview
on:
  workflow_run:
    workflows:
      - trigger-site-build
    types:
      - requested
      - completed

jobs:
  automate-metrics:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Automate Metrics
        env:
          PORTAL_ID: ${{  secrets.PORTAL_ID }}
          FOUNDATIONS_ID: ${{ secrets.FOUNDATIONS_ID }}
          COOKBOOKS_ID: ${{ secrets.COOKBOOKS_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        run: |
          python -m venv analytics-api
          source analytics-api/bin/activate
          pip install google-analytics-data cartopy matplotlib

          curl -O https://raw.githubusercontent.com/jukent/projectpythia.github.io/main/.github/workflows/get-metrics.py
          curl -O https://raw.githubusercontent.com/jukent/projectpythia.github.io/main/.github/workflows/write-metrics-md.py

          python get-metrics.py
          python write-metrics-md.py

  find-pull-request:
    uses: ProjectPythia/cookbook-actions/.github/workflows/find-pull-request.yaml@main
  deploy-preview:
    needs: find-pull-request
    needs: automate-metrics
    if: github.event.workflow_run.conclusion == 'success'
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
    with:
      artifact_name: book-zip-${{ needs.find-pull-request.outputs.number }}
      destination_dir: _preview/${{ needs.find-pull-request.outputs.number }}  # deploy to subdirectory labeled with PR number
      is_preview: 'true'
      cname: projectpythia.org
      publish_dir: 'portal/_build/html'

  preview-comment:
    needs: find-pull-request
    uses: ProjectPythia/cookbook-actions/.github/workflows/preview-comment.yaml@main
    with:
      pull_request_number: ${{ needs.find-pull-request.outputs.number }}
      sha: ${{ needs.find-pull-request.outputs.sha }}
