name: trigger-site-build
on:
  pull_request:

jobs:
  update-metrics:
    uses: automate-metrics.yaml@main

  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_file: 'environment.yml'
      environment_name: pythia
      artifact_name: book-zip-${{ github.event.number }}
      path_to_notebooks: 'portal'
      build_command: 'make -j4 html'
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml
